name: "Release developer"

on:

  push:

    branches:

      - "main"

jobs:
  build:
    name: Build and test
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        psbuilder-version: ["1.0"]
    steps:
      - uses: actions/checkout@v2
      - name: setup PsBuilder
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.psbuilder-version }}
          repository: psbuilder/psbuilder
          path: builder
          
      
      - name: Build and test
        run: |
          
          ./builder/PsBuilder.init.ps1
        shell: pwsh
  analyze:
    name: "Analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze
        shell: pwsh
        run: |
          Install-Module PsScriptAnalyzer -Force
          Invoke-ScriptAnalyzer -Path ./

  pre-release:

    name: "Pre-release version"
    needs: [build, analyze]
    runs-on: "ubuntu-latest"

    steps:

      # ...
      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"

        with:

          repo_token: "${{ secrets.GITHUB_TOKEN }}"

          automatic_release_tag: "dev"

          prerelease: true

          title: "Dev build"

          files: |


            ./cshell-devs.ps1
