

name: "pre-release"

on:

  push:

    branches:

      - "main"

jobs:

  pre-release:

    name: "Pre Release"

    runs-on: "ubuntu-latest"

    steps:

      # ...
      - run: git clone https://github.com/psbuilder/psbuilder.git
      - name: "Build & test"
 
        run: |
          cd ./
          PsBuilder.ps1
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"

        with:

          repo_token: "${{ secrets.GITHUB_TOKEN }}"

          automatic_release_tag: "dev"

          prerelease: true

          title: "Dev build"

          files: |

            LICENSE

            *.ps1
