on:

    push:

        branches:

            - main

    
            

name: Wiki Sync

jobs:

    update-wiki:

        runs-on: ubuntu-latest

        steps:

          - uses: actions/checkout@master

          - name: Sync Wiki

            uses: joeizzard/action-wiki-sync@master

            with:

                username: ControllerShell

                access_token: ${{ secrets.GITHUB_TOKEN }}

                wiki_folder: wiki

                commit_username: 'WikiSync'

                commit_email: 'github-actions[bot]@users.noreply.github.com'

                commit_message: 'Automated wiki sync'
