on:

    push:

        branches:

            - main

    pull_request:

        branches:

            - main

name: Wiki Sync

jobs:

    update-wiki:

        runs-on: ubuntu-latest

        steps:

          - uses: actions/checkout@master

          - name: Sync Wiki

            uses: joeizzard/action-wiki-sync@master

            with:

                username: Consopedia

                access_token: ${{ secrets.GITHUB_TOKEN }}

                wiki_folder: wiki

                commit_username: 'ConsoPedia'

                commit_email: 'Tyler887@users.noreply.github.com'

                commit_message: 'Wiki sync'
