on:

    push:

        branches:

            - main

    
            

name: Wiki Sync

jobs:

    update-wiki:

        runs-on: ubuntu-latest

        steps:

          - uses: actions/checkout@master

          - name: Sync Wiki

            uses: joeizzard/action-wiki-sync@master

            with:

                username: ${{github.events.actor}}

                access_token: ${{ secrets.GITHUB_TOKEN }}

                wiki_folder: wiki

                commit_username: '${{ github.events.actor }} (via source code)'

                commit_email: '${{ github.events.actor }}@users.noreply.github.com'

                commit_message: 'Wiki sync'
